name: Continuous Integration

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "!master"
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    name: Build, Tests

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Run build
        run: |
          dotnet build --configuration Release ./src/Specification/Specification.csproj

      - name: Run UnitTests
        run: |    
          dotnet test --configuration Release ./tests/Specification.Tests/Specification.Tests.csproj

      - name: Run IntegrationTests
        run: |    
          dotnet test --configuration Release ./tests/Specification.IntegrationTests/Specification.IntegrationTests.csproj